version: "3.9"

services:
  web:
    container_name: ${PROJECT_NAME}_web
    build: ./tourist_archive
    image: mkvasco/${IMAGE_NAME}-web
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
    name: tourist_archive_network
